name: Deploy to VPS

on:
  push:
    branches:
      - ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 62.3.41.12
          username: secureadmin
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/secureadmin/backend/backend--agent
            ./deploy.sh
